services:
  env-generator:
    build:
      context: .
      target: app-env
    volumes:
      - shared_env:/shared_env
    healthcheck:
      test: ["CMD", "test", "-f", "/shared_env/.env"]
      interval: 2s
      retries: 3
      start_period: 1s
      timeout: 2s

  db_mock:
    image: busybox
    depends_on:
      env-generator:
        condition: service_healthy
    volumes:
      - shared_env:/shared_env
    command: ["sh", "-c", ". /shared_env/.env && env"]

volumes:
  shared_env: