version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
    command: poetry run python ./src/main.py

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${database_username}
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=${database_name}

  tests:
    build: .
    command: pytest
    depends_on:
      - db