[tool.poetry]
name = "bwiseth-extract"
version = "0.1.0"
description = "Extraction of raw data from public APIs and writing to database."
authors = ["Oscar Gil <hello@oscargilbalaguer.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pulumi = "^3.133.0"
pulumi-aws = "^6.52.0"
sqlalchemy = "^2.0.35"
black = "^24.10.0"
isort = "^5.13.2"
ruff = "^0.7.0"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
